### ISSUE TITLE
After successful flash, logs suggest failure

### ISSUE THREAD

**Issue by chrisys** [balenablocks/fin#5]
Immediately after a flash which appears to have been successful (works OK after rebooting), there was a message in the logs saying flashing most likely failed - see below. This could be misleading for users.

![Screenshot 2020-10-12 at 13 27 15](https://user-images.githubusercontent.com/521698/95746594-f4fc5900-0c8e-11eb-9d65-dd80cc2880a5.png)

**Comment by Bucknalla** [comment]
#31 handles this
